export const NotificationType = {
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  TOUR_APPROVAL_REQUIRED: "TOUR_APPROVAL_REQUIRED",
  TOUR_APPROVED: "TOUR_APPROVED",
  CANCELLATION_ALERT: "CANCELLATION_ALERT",
  ONE_WEEK_TRAVEL_REMINDER: "ONE_WEEK_TRAVEL_REMINDER",
  SYSTEM_ALERT: "SYSTEM_ALERT",
  REQUEST_CREATED: "REQUEST_CREATED",
  REQUEST_ASSIGNED: "REQUEST_ASSIGNED",
  REQUEST_SOLVED: "REQUEST_SOLVED",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  TOUR_COMPLETED: "TOUR_COMPLETED"
} as const;

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];

export const NotificationTypeColor = {
  BOOKING_CONFIRMED: "green", TOUR_APPROVAL_REQUIRED: "orange", TOUR_APPROVED: "teal",
  CANCELLATION_ALERT: "red", ONE_WEEK_TRAVEL_REMINDER: "purple", SYSTEM_ALERT: "gray",
  REQUEST_CREATED: "blue", REQUEST_ASSIGNED: "yellow", REQUEST_SOLVED: "teal",
  REQUEST_REJECTED: "red", TOUR_COMPLETED: "green",
} as const;
